name: linearb-metrics-watch

on:
  schedule:
    - cron: "0 1 * * *"  # 毎日 JST 10:00
  workflow_dispatch:      # 手動実行も可能にする

jobs:
  create_issue_if_needed:
    runs-on: ubuntu-latest
    steps:
      - name: Check metrics & create Linear issue
        env:
          LB_TOKEN: ${{ secrets.LB_TOKEN }}
          LINEAR_TOKEN: ${{ secrets.LINEAR_TOKEN }}
          LINEAR_TEAM_ID: ${{ secrets.LINEAR_TEAM_ID }}
        run: |
          pip install requests --quiet
          python <<'PY'
          import os, requests, datetime, textwrap, json
          LB, LIN, TEAM = os.environ['LB_TOKEN'], os.environ['LINEAR_TOKEN'], os.environ['LINEAR_TEAM_ID']
          # ① LinearB 直近1週の Pickup 平均取得
          since = (datetime.date.today() - datetime.timedelta(days=7)).isoformat()
          payload = {
              "from": since,
              "metrics": ["cycle-time.pickup"],
              "aggregate": "average"
          }
          res = requests.post(
              "https://public-api.linearb.io/api/v2/measurements",
              headers={"x-api-key": LB, "Content-Type": "application/json"},
              json=payload, timeout=30
          )
          pickup = res.json()["cycle-time.pickup"]["average"]  # minutes

          if pickup < 8*60:
              print(f"✅ OK ({pickup/60:.1f}h < 8h)")
              quit()

          # ② Linear に Issue を作成
          title = f"[Auto] Pickup exceeds 8h ({pickup/60:.1f}h)"
          desc = textwrap.dedent(f"""
          ### 問題
          Pickup 平均が **{pickup/60:.1f} 時間** と目標 8h を超過

          ### 原因候補
          - Reviewer 固定
          - PR サイズ過大

          ### 対策候補
          - CODEOWNERS 整備
          - PR 分割ルール・danger/large-pr 設定
          """)

          gql = "mutation($in: IssueCreateInput!) { issueCreate(input: $in) { issue { identifier url } } }"
          variables = { "in": { "teamId": TEAM, "title": title, "description": desc } }

          r = requests.post(
              "https://api.linear.app/graphql",
              json={"query": gql, "variables": variables},
              headers={"Authorization": LIN}, timeout=30
          )
          print("✅ Linear Issue created:", r.json()["data"]["issueCreate"]["issue"]["url"])
          PY
